openapi: 3.0.3
info:
  title: HatoMask API - Photo Upload
  description: |
    写真アップロード（静止画）機能の API 仕様。

    ## データ取り扱い（Milestone 0）
    本 API は実在写真（入力由来ベース）を扱う可能性があるため、画像データおよび派生データは永続化しません。
    - 永続化禁止（DB/ストレージ/キャッシュ/バックアップ等に保存しない）
    - 短命 TTL（原則リクエストスコープ）
    - 非ログ（画像データ/派生データ/入力ファイル名などをログ・テレメトリへ出さない）

    目的は、画像ファイルのバリデーションとデコードを行い、プレビュー/後続機能が利用できる最小限のメタ情報を返すことです。
  version: 1.0.0
  contact:
    name: HatoMask Development Team

servers:
  - url: http://localhost:8080/api/v1
    description: ローカル開発環境
  - url: http://localhost:5173/api/v1
    description: フロントエンド開発サーバー（MSW）

tags:
  - name: photos
    description: 写真アップロード

paths:
  /photos:
    post:
      tags:
        - photos
      summary: 写真をアップロード（検証・デコード）
      description: |
        静止画（JPEG/PNG）を受け取り、サイズ/形式を検証し、デコードしてメタ情報を返します。
        Milestone 0 では画像および派生データを永続化しません（短命・非ログ）。

        ### ビジネスルール
        - 最大ファイルサイズ: 10MB
        - 対応形式: JPEG / PNG

        ### 注意
        - 入力ファイル名は契約上もレスポンスに含めません（非ログ方針のため）。
      operationId: uploadPhoto
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: アップロードする写真ファイル（JPEG/PNG）
              required:
                - file
      responses:
        "200":
          description: バリデーション成功・デコード成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadPhotoResponse"
        "400":
          description: バリデーションエラー（形式不一致、サイズ超過など）
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                fileSizeExceeded:
                  summary: ファイルサイズ超過
                  value:
                    type: "about:blank"
                    title: "Bad Request"
                    status: 400
                    detail: "ファイルサイズは10MB以下にしてください"
                invalidFormat:
                  summary: 非対応形式
                  value:
                    type: "about:blank"
                    title: "Bad Request"
                    status: 400
                    detail: "JPEG または PNG ファイルを選択してください"
        "422":
          description: デコード失敗
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                type: "about:blank"
                title: "Unprocessable Entity"
                status: 422
                detail: "画像のデコードに失敗しました"
        "500":
          description: サーバーエラー
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

components:
  schemas:
    UploadPhotoResponse:
      type: object
      description: |
        アップロード画像のメタ情報。
        画像本体は返しません（プレビューはクライアント側で行う前提）。
      properties:
        mimeType:
          type: string
          description: MIME type
          enum:
            - image/jpeg
            - image/png
        sizeBytes:
          type: integer
          format: int64
          description: ファイルサイズ（バイト）
          minimum: 0
          maximum: 10485760
        widthPx:
          type: integer
          format: int32
          description: 画像幅（px）
          minimum: 1
        heightPx:
          type: integer
          format: int32
          description: 画像高さ（px）
          minimum: 1
      required:
        - mimeType
        - sizeBytes
        - widthPx
        - heightPx
      example:
        mimeType: image/jpeg
        sizeBytes: 5242880
        widthPx: 1920
        heightPx: 1080

    ProblemDetails:
      type: object
      description: |
        RFC 9457準拠のエラーレスポンス。
        全てのAPIエラーはこの形式で返却される。
      properties:
        type:
          type: string
          description: |
            問題タイプを識別するURI。
            通常は "about:blank" を使用。
          example: "about:blank"
        title:
          type: string
          description: 人間が読める短いエラー概要
          example: "Bad Request"
        status:
          type: integer
          description: HTTPステータスコード
          example: 400
        detail:
          type: string
          description: 問題の詳細な説明
          example: "Validation failed"
        instance:
          type: string
          description: 問題が発生したリクエストのURI（オプション）
        errors:
          type: array
          description: バリデーションエラーの詳細（オプション）
          items:
            type: object
            properties:
              field:
                type: string
                description: エラーが発生したフィールド名
              message:
                type: string
                description: エラーメッセージ
      required:
        - type
        - title
        - status
